### ISSUE TITLE
Shelve notice.

### ISSUE THREAD

**Issue by xiazeyu** [xiazeyu/live2d-widget.js#38]
# TODO

## NOTICE

To prepare for the College Entrance Examination, I decided to put the project off for a year.

为了准备高考, 我准备将此项目搁置一年.

Any question please contant [EYHN](https://github.com/xiazeyu/live2d-widget.js#about-me).

Thanks for all your supports. See you next summer vacation.

## File list

- [x] │   .babelrc

- [x] │   .codeclimate.yml

- [x] │   .czrc

- [x] │   .editorconfig

- [x] │   .esdoc.json

- [x] │   .eslintignore

- [x] │   .eslintrc.js

- [x] │   .gitignore

- [x] │   .gitmodules

- [x] │   .mdlrc

- [x] │   .npmignore

- [x] │   .travis.yml

- [x] │   CHANGELOG.md

- [x] │   jsconfig.json

- [x] │   LICENSE

- [x] │   package-lock.json

- [x] │   package.json

- [x] │   playground.html

- [x] │   README.md

- [x] │   TO-DO.md

- [x] │   webpack.config.js

- [x] │   yarn.lock

- [x] ├───.github

- [x] │   │   CODE_OF_CONDUCT.md

- [x] │   │   CONTRIBUTING.md

- [x] │   │   ISSUE_TEMPLATE.md

- [x] │   │   PULL_REQUEST_TEMPLATE.md

- [x] │   └───ISSUE_TEMPLATE

- [x] │           bug-report-----.md

- [x] │           bug_report.md

- [x] │           feature-request------.md

- [x] │           feature_request.md

- [x] ├───.vscode

- [x] │       settings.json

- [x] ├───build

- [x] │       afterBuild.js

- [x] │       afterCIBuild.js

- [x] │       deployDocs.sh

- [x] │       generator.html

- [x] │       getProjPath.js

- [x] │       id_rsa.enc

- [x] │       playgroundProduction.html

- [x] │       playgroundProductionv3.html

- [x] │       ssh_config

- [ ] └───src

- [ ]     │   elementMgr.js

- [ ]     │   index.js

- [ ]     │   index_.js

- [ ]     │   main.js

- [ ]     │   main_.js

- [ ]     │   Model.js

- [ ]     │   ModelManager.js

- [ ]     │   Model_.js

- [ ]     │   Storage.js

- [x]     ├───config

- [x]     │       configMgr.js

- [x]     │       configStorage.js

- [ ]     ├───lib

- [ ]     │       BaseModel.js

- [ ]     │       ExpressionMotion.js

- [ ]     │       ExpressionParam.js

- [ ]     │       EyeBlink.js

- [x]     │       live2d.core.nodoc.js

- [ ]     │       MotionManager.js

- [ ]     │       PartsParam.js

- [ ]     │       Physics.js

- [ ]     │       polyfill.nodoc.js

- [ ]     │       Pose.js

- [ ]     │       setEnv.nodoc.js

- [ ]     │       TargetPoint.js

- [x]     ├───tmplate

- [x]     │       innerHTML.html

- [ ]     └───utils

- [ ]             Matrix.js

- [ ]             ModelSettingJson.js

- [x]             pathHandler.js

- [ ]             PlatformManager.js

**Comment by xiazeyu** [comment]
http://www.cnblogs.com/pcyy/p/5655542.html
https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/Tutorial/Basic_animations
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onafterprint
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint
https://developer.mozilla.org/zh-CN/docs/Web/API/GlobalEventHandlers/onresize
https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener
https://developer.mozilla.org/en-US/docs/Web/API/Window/screen
https://developer.mozilla.org/en-US/docs/Web/API/Screen
https://eslint.org/docs/rules/getter-return

**Comment by linonetwo** [comment]
高考加油，期待更新

**Comment by imgss** [comment]
居然是高中生，厉害了

**Comment by potoo0** [comment]
Holy shit! Unbelieveable.
